### ISSUE TITLE
Decision for win/loss/draw

### ISSUE THREAD

**Issue by mlsdpk** [mlsdpk/alphazero-checkers-pygame#13]
Need to discuss how to decide win/loss/draw conditions.

**Comment by aungpaing98** [comment]
I will use these rules to decide winner/draw:

1. If a player has lost all his pieces he loses.
2. If a player can't move at all, all his pieces are blocked, he loses.
3. The exact same board state has come up three times without any men captured in between. The game ends in a draw. This is to avoid situation with two pieces left just moving around never being able to capture each other.
4. There have been 100 moves (50 for each player) with no piece captured. The game ends in a draw.

I could use some help with rule no. 3. @Awthura .
